name: Metrics Web Application Actions

on:
  push:
    branches: master

jobs:
  metrics-actions:
    name: Metrics actions
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_RELEASE: ${{ github.run_number }}
      SENTRY_RELEASE_AUTORENDERER: ${{ github.run_number }}_autorenderer
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_TOKEN_PRODUCTION: ${{ secrets.FIREBASE_TOKEN_PRODUCTION }}
      GOOGLE_SIGN_IN_CLIENT_ID: ${{ secrets.GOOGLE_SIGN_IN_CLIENT_ID }}
      GOOGLE_SIGN_IN_CLIENT_ID_PRODUCTION: ${{ secrets.GOOGLE_SIGN_IN_CLIENT_ID_PRODUCTION }}
      PRODUCTION_PROJECT_NAME: ${{ secrets.PRODUCTION_PROJECT_NAME }}
      PRODUCTION_HOSTING_NAME: ${{ secrets.PRODUCTION_HOSTING_NAME }}
      PROJECT_PATH: metrics/web/
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - uses: subosito/flutter-action@v1
        with:
          channel: beta
          flutter-version: 1.25.0-8.2.pre

      - uses: cedx/setup-dart@v2
        with:
          release-channel: beta
          version: 2.12.0-133.2.beta

      - name: Configure Flutter
        run: flutter config --enable-web && flutter doctor
        working-directory: metrics/web/

      - name: Get dependencies
        run: flutter pub get
        working-directory: metrics/web/

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Install Sentry CLI
        run: brew install getsentry/tools/sentry-cli

      - name: Build release app
        run: flutter clean && flutter build web --release --source-maps
        working-directory: metrics/web/

      - name: Prepare metrics config for dev environment
        run: |
          export SENTRY_ENVIRONMENT="development"
          : > build/web/metrics_config.js
          eval "echo \"$(sed 's/"/\\"/g' web/metrics_config.js)\"" >> build/web/metrics_config.js
        working-directory: metrics/web/

      - name: Update Source Maps for HTML app version
        run: |
          sentry-cli releases new $SENTRY_RELEASE
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps . --ext dart --rewrite
          cd ./build/web/
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps . --ext map --ext js --rewrite
          sentry-cli releases finalize $SENTRY_RELEASE
        working-directory: metrics/web/

      - name: Deploy HTML version to Firebase
        run: |
          firebase target:apply hosting metrics test-prod-1-17a8e
          firebase deploy --only hosting:metrics
        working-directory: metrics/web/

      - name: Switch to Flutter latest master version
        run: flutter channel master && flutter upgrade
        working-directory: metrics/web/

      - name: Build release app using auto renderer
        run: flutter clean && flutter build web --release --source-maps --dart-define=FLUTTER_WEB_AUTO_DETECT=true
        working-directory: metrics/web/

      - name: Prepare metrics config for dev skia environment
        env:
          SENTRY_RELEASE: ${{ env.SENTRY_RELEASE_AUTORENDERER }}
        run: |
          export SENTRY_ENVIRONMENT="development-skia"
          : > build/web/metrics_config.js
          eval "echo \"$(sed 's/"/\\"/g' web/metrics_config.js)\"" >> build/web/metrics_config.js
        working-directory: metrics/web/

      - name: Update Source Maps for auto renderer app version
        run: |
          sentry-cli releases new $SENTRY_RELEASE_AUTORENDERER
          sentry-cli releases files $SENTRY_RELEASE_AUTORENDERER upload-sourcemaps . --ext dart --rewrite
          cd ./build/web/
          sentry-cli releases files $SENTRY_RELEASE_AUTORENDERER upload-sourcemaps . --ext map --ext js --rewrite
          sentry-cli releases finalize $SENTRY_RELEASE_AUTORENDERER
        working-directory: metrics/web/

      - name: Deploy auto renderer version to Firebase
        run: |
          firebase target:apply hosting metrics test-prod-1-site2
          firebase deploy --only hosting:metrics
        working-directory: metrics/web/

      - name: Prepare metrics config for production environment
        env:
          SENTRY_RELEASE: ${{ env.SENTRY_RELEASE_AUTORENDERER }}
          GOOGLE_SIGN_IN_CLIENT_ID: ${{ env.GOOGLE_SIGN_IN_CLIENT_ID_PRODUCTION }}
        run: |
          export SENTRY_ENVIRONMENT="production-skia"
          : > build/web/metrics_config.js
          eval "echo \"$(sed 's/"/\\"/g' web/metrics_config.js)\"" > build/web/metrics_config.js
        working-directory: metrics/web/

      - name: Update Firebase Hosting configuration for production
        run: |
          eval "echo \"$(sed 's/"/\\"/g' .firebaserc)\"" > .firebaserc
          eval "echo \"$(sed 's/"/\\"/g' firebase.json)\"" > firebase.json
        working-directory: metrics/web/

      - name: Deploy auto renderer version to Firebase
        env:
          FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN_PRODUCTION }}
        run: |
          firebase use --add $PRODUCTION_PROJECT_NAME
          firebase target:apply hosting metrics $PRODUCTION_HOSTING_NAME
          firebase deploy --only hosting:metrics
        working-directory: metrics/web/
